<?php return array (
  'site_title' => 'Prophecy',
  'base_color' => '#8fb568',
  'time_zone' => 'UTC',
  'currency' => 'USD',
  'currency_symbol' => '$',
  'theme' => 'betting',
  'fraction_number' => 0,
  'paginate' => 20,
  'email_verification' => 0,
  'email_notification' => 0,
  'sms_verification' => 0,
  'sms_notification' => 0,
  'push_notification' => 1,
  'error_log' => 0,
  'strong_password' => 0,
  'registration' => 1,
  'address_verification' => 0,
  'identity_verification' => 0,
  'maintenance' => 0,
  'is_active_cron_notification' => 1,
  'sender_email' => 'support@mail.com',
  'sender_email_name' => 'Bug Finder',
  'email_configuration' => 
  array (
    'name' => 'smtp',
    'smtp_host' => 'smtp.mailtrap.io',
    'smtp_port' => '2525',
    'smtp_encryption' => 'ssl',
    'smtp_username' => 'b75b1a5bfa5d58',
    'smtp_password' => 'f89fbe0495a7fc',
  ),
  'win_charge' => '0',
  'refund_charge' => '5',
  'minimum_bet' => '5',
  'deposit_commission' => 0,
  'bet_commission' => 0,
  'bet_win_commission' => 0,
  'theme_mode' => 0,
);